### ISSUE TITLE
Reduce inference of unknown data/location for SRA sequences

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/avian-flu#65]
Discussed in [Nextstrain biweekly meeting on 2024-06-27](https://docs.google.com/document/d/11QxlSnizl9DCFGOiLQQlI4LiIFoQKlVXtpLdL0TstqM/edit#heading=h.trhbpuz1ove9)

Because the SRA data ingested from Andersen Lab does not have precise date or location metadata, there's a lot of inference in the [h5n1-cattle-outbreak tree](https://next.nextstrain.org/avian-flu/h5n1-cattle-outbreak/genome@2024-06-25?c=division). 

A couple suggestions to reduce inference
- [x] add CIs to time (augur refine setting) -> [we are already doing this](https://github.com/nextstrain/avian-flu/blob/96d4f9d0c1f0739f5210fe80fadc521d4344c8fe/Snakefile.genome#L200)
- [x] make divergence the default view -> set default `distance_measure` to `div` in [Auspice config's display_defaults](https://github.com/nextstrain/avian-flu/blob/96d4f9d0c1f0739f5210fe80fadc521d4344c8fe/config/auspice_config_h5n1-cattle-outbreak.json#L119-L123)
- [x] ~just use location metadata without ancestral reconstruction -> remove [traits rule](https://github.com/nextstrain/avian-flu/blob/96d4f9d0c1f0739f5210fe80fadc521d4344c8fe/Snakefile.genome#L243-L260)~ See alternative methods explored by @trvrb in https://github.com/nextstrain/avian-flu/pull/66#issuecomment-2195810607

**Comment by jameshadfield** [comment]
> add CIs to time (augur refine setting) -> [we are already doing this](https://github.com/nextstrain/avian-flu/blob/96d4f9d0c1f0739f5210fe80fadc521d4344c8fe/Snakefile.genome#L200)

You're right! For some reason this toggle wasn't showing when Trevor was demo-ing it in the meeting, or did I miss it? Here's the temporally inferred Idaho clade (which may not be all Idaho!)

<img width="1011" alt="image" src="https://github.com/nextstrain/avian-flu/assets/8350992/cd59157c-9f09-48f7-9a70-d63027be6e6a">
