### ISSUE TITLE
Not able to build / download data sets

### ISSUE THREAD

**Issue by kiranpatil222** [nextstrain/avian-flu#83]
### Current Behavior
`snakemake --cores 1 -pf --configfile config/gisaid.yaml`

Error:
```
download failed: s3://nextstrain-data-private/files/workflows/avian-flu/ha/sequences.fasta.zst to - Unable to locate credentials
zstd: /*stdin*\: unexpected end of file

aws s3 cp s3://nextstrain-data-private/files/workflows/avian-flu/ha/sequences.fasta.zst - | zstd -d > data/gisaid/sequences_ha.fasta

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

```

### Your environment: if browsing Nextstrain online
 - Ubutu 18
 - Browser:

### Your environment: if running Nextstrain locally
 - Ubuntu 18
 - nextstrain.cli 8.2.0

**Comment by genehack** [comment]
That build requires data obtained from GISAID, which we are not allowed to redistribute. You will not be able to run that build without modifying it. 

The README file at the top level of this repo contains [instructions on modifying the build](https://github.com/nextstrain/avian-flu/?tab=readme-ov-file#to-modify-this-build-to-work-with-your-own-data) to work with local data files, and how to run the build with sample data contained in the repo.

**Comment by genehack** [comment]
@kiranpatil222 is there any other assistance I can provide here? Otherwise I will close this issue out as resolved.

**Comment by kiranpatil222** [comment]
Hi @genehack Thank you for reply, this same process worked SarsCov2 and other organisms, i was wondering why this did not work for this,,!
Do i have to download data from GISAID or our own data and then Build test it ?

**Comment by genehack** [comment]
> Hi @genehack Thank you for reply, this same process worked SarsCov2 and other organisms, i was wondering why this did not work for this,,! 

I'm not sure which Covid or other organism builds you're trying, but I have to assume they're not dependent on GISAID data. 

> Do i have to download data from GISAID or our own data and then Build test it ?

If you have access to GISAID data, downloading it and then following the [documentation about local data builds](https://github.com/nextstrain/avian-flu/?tab=readme-ov-file#to-modify-this-build-to-work-with-your-own-data) would be a way forward, yes.

**Comment by genehack** [comment]
Hi @kiranpatil222, based on lack of further replies, I'm going to assume I addressed your issues and close this ticket out. Please reply if you have additional questions, thanks!
