### ISSUE TITLE
ERROR: Augur version incompatibility detected

### ISSUE THREAD

**Issue by Wen1953** [nextstrain/avian-flu#9]
Hi, I'm trying to run the quickstart-build for avian-flu, but I got this error. I'm using nextstrain.cli v.6.2.1 and augur v.19.2.0. Some idea to fix it?

·································
ERROR: Augur version incompatibility detected: the JSON results/branch-lengths_h5n1_ha.json was generated by {'program': 'augur', 'version': '19.2.0'}, which is incompatible with the current augur version (21.1.0). We suggest you rerun the pipeline using the current version of augur.
[Tue Apr 18 21:08:44 2023]

Error in rule export:
jobid: 1
input: results/tree_h5n1_ha.nwk, results/metadata_h5n1_ha.tsv, results/branch-lengths_h5n1_ha.json, results/traits_h5n1_ha.json, results/nt-muts_h5n1_ha.json, results/aa-muts_h5n1_ha.json, results/cleavage-site_h5n1_ha.json, results/cleavage-site-sequences_h5n1_ha.json, config/auspice_config_h5n1.json
output: auspice/flu_avian_h5n1_ha.json
shell:
        
augur export v2             --tree results/tree_h5n1_ha.nwk             --metadata results/metadata_h5n1_ha.tsv             --node-data results/branch-lengths_h5n1_ha.json results/traits_h5n1_ha.json results/nt-muts_h5n1_ha.json results/aa-muts_h5n1_ha.json results/cleavage-site_h5n1_ha.json results/cleavage-site-sequences_h5n1_ha.json            --auspice-config config/auspice_config_h5n1.json             --include-root-sequence             --output auspice/flu_avian_h5n1_ha.json

(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-04-18T210843.145552.snakemake.log
···································

**Comment by jameshadfield** [comment]
That error indicates that intermediate files from a previous run [1] exist, however you are rerunning the pipeline with a newer version of Augur. The easiest solution is to remove the intermediate files (e.g. remove the `results` directory, or rename it if you want to keep a backup) and rerun the pipeline; this will force the pipeline to rerun every step with your current augur version.

> I'm using ... augur v.19.2.0

The error indicates that you are now using "augur version (21.1.0)", but that a previous run of the workflow used 19.2.0. Note that if you are running the pipeline using a nextstrain-cli provided runtime (e.g. Docker, managed conda) then the version of augur used by the pipeline may be different to `augur --version`. If you let us know what command you are running the pipeline, as well as the output of `nextstrain check-setup`, we can help troubleshoot this.

[1] Specifically, `results/branch-lengths_h5n1_ha.json` was generated by Augur version 19.2.0

**Comment by Wen1953** [comment]
The commands that I used in the running were:
https://github.com/nextstrain/avian-flu/tree/master/quickstart-build
```
git clone https://github.com/nextstrain/avian-flu.git
cd avian-flu
nextstrain build quickstart-build/ --dry-run
nextstrain build quickstart-build/
After that I get the error.
```

As you say I think is a problem with the different version of augur between the running and the avian-flu example. After change the version of augur inside the files the error disappear. The `results/branch-lengths_h5n1_ha.json` file was created with Augur version 19.2.0 and it cames with the data, so I can't create a new one.

**Comment by tsibley** [comment]
> The `results/branch-lengths_h5n1_ha.json` file was created with Augur version 19.2.0 and it cames with the data, so I can't create a new one.

Ah, it probably shouldn't come with the repo. And indeed, it looks like @lmoncla [already removed it](https://github.com/nextstrain/avian-flu/commit/e44af809234b4ab563692e728b46456423667b67) (and related files in `results/`).
