### ISSUE TITLE
Extend oropouche segment-matching approach to avian flu

### ISSUE THREAD

**Issue by genehack** [nextstrain/avian-flu#92]
Extend the [prototype segment-merging approach implemented for oropouche](https://github.com/nextstrain/oropouche/pull/18) to NCBI Avian-flu.

**Comment by jameshadfield** [comment]
This was done in https://github.com/nextstrain/avian-flu/pull/93 and we (@joverlee521 & I) decided to put it on ice and test out #82 and compare the results.
