### ISSUE TITLE
Restore timetree default to H5N1 cattle outbreak genome analysis

### ISSUE THREAD

**Issue by trvrb** [nextstrain/avian-flu#94]
We had swapped the default `h5n1-cattle-outbreak` view to be divergence rather than time tree due to the previously excessive extrapolation from divergence to time via molecular clock because of lack of metadata on SRA. However, at this point we have three things going on:
1. Timeline from SRA to GenBank has improved and so it's only the last ~1 month of tips that are getting dates inferred
2. Time window for this last month has decreased relative to the span of the outbreak making a clock estimate easier
3. We have funny outliers in the divergence view that obscure overall picture

<img width="1193" alt="Screenshot 2024-10-09 at 11 33 24 AM" src="https://github.com/user-attachments/assets/d819c814-487c-400b-967a-675fff53296d">

I'd propose that we swap default `distance_measure` here: https://github.com/nextstrain/avian-flu/blob/master/config/h5n1-cattle-outbreak/auspice_config_h5n1-cattle-outbreak.json#L127, back to `num_date`.

However, this should only be done for https://nextstrain.org/avian-flu/h5n1-cattle-outbreak/genome, the segment-level trees like https://nextstrain.org/avian-flu/h5n1-cattle-outbreak/ha should keep divergence as default.

This is kind of annoying in that I'd like to avoid 9 different Auspice configs keyed to different wildcards.

Ideally here we'd have the simple system of Auspice config override that's been discussed before
- https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1622071387034200?thread_ts=1622004897.033100&cid=C01LCTT7JNN

cc @jameshadfield

**Comment by jameshadfield** [comment]
> Ideally here we'd have the simple system of Auspice config override that's been discussed before

Yes (we've all agreed to this in principle many times before, someone just needs to work out the details of how merging works). Unfortunately we can't use command line arguments to override the `display_defaults`. 

I can implement a temporary solution tomorrow (or thereabouts) where we add a `rule auspice_config:` and modify things conditional on wildcards.

**Comment by trvrb** [comment]
Thanks James! No real urgency here. I just added the divergence outliers to the dropped strains list: https://github.com/nextstrain/avian-flu/commit/e98c98c90bee706622ca70d91c809bebcddcda21, so this should clean up the default divergence in the interim.
